require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CustomizedConceptsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CustomizedConcept. As you add validations to CustomizedConcept, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CustomizedConceptsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all customized_concepts as @customized_concepts" do
      customized_concept = CustomizedConcept.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:customized_concepts)).to eq([customized_concept])
    end
  end

  describe "GET #show" do
    it "assigns the requested customized_concept as @customized_concept" do
      customized_concept = CustomizedConcept.create! valid_attributes
      get :show, {:id => customized_concept.to_param}, valid_session
      expect(assigns(:customized_concept)).to eq(customized_concept)
    end
  end

  describe "GET #new" do
    it "assigns a new customized_concept as @customized_concept" do
      get :new, {}, valid_session
      expect(assigns(:customized_concept)).to be_a_new(CustomizedConcept)
    end
  end

  describe "GET #edit" do
    it "assigns the requested customized_concept as @customized_concept" do
      customized_concept = CustomizedConcept.create! valid_attributes
      get :edit, {:id => customized_concept.to_param}, valid_session
      expect(assigns(:customized_concept)).to eq(customized_concept)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CustomizedConcept" do
        expect {
          post :create, {:customized_concept => valid_attributes}, valid_session
        }.to change(CustomizedConcept, :count).by(1)
      end

      it "assigns a newly created customized_concept as @customized_concept" do
        post :create, {:customized_concept => valid_attributes}, valid_session
        expect(assigns(:customized_concept)).to be_a(CustomizedConcept)
        expect(assigns(:customized_concept)).to be_persisted
      end

      it "redirects to the created customized_concept" do
        post :create, {:customized_concept => valid_attributes}, valid_session
        expect(response).to redirect_to(CustomizedConcept.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved customized_concept as @customized_concept" do
        post :create, {:customized_concept => invalid_attributes}, valid_session
        expect(assigns(:customized_concept)).to be_a_new(CustomizedConcept)
      end

      it "re-renders the 'new' template" do
        post :create, {:customized_concept => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested customized_concept" do
        customized_concept = CustomizedConcept.create! valid_attributes
        put :update, {:id => customized_concept.to_param, :customized_concept => new_attributes}, valid_session
        customized_concept.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested customized_concept as @customized_concept" do
        customized_concept = CustomizedConcept.create! valid_attributes
        put :update, {:id => customized_concept.to_param, :customized_concept => valid_attributes}, valid_session
        expect(assigns(:customized_concept)).to eq(customized_concept)
      end

      it "redirects to the customized_concept" do
        customized_concept = CustomizedConcept.create! valid_attributes
        put :update, {:id => customized_concept.to_param, :customized_concept => valid_attributes}, valid_session
        expect(response).to redirect_to(customized_concept)
      end
    end

    context "with invalid params" do
      it "assigns the customized_concept as @customized_concept" do
        customized_concept = CustomizedConcept.create! valid_attributes
        put :update, {:id => customized_concept.to_param, :customized_concept => invalid_attributes}, valid_session
        expect(assigns(:customized_concept)).to eq(customized_concept)
      end

      it "re-renders the 'edit' template" do
        customized_concept = CustomizedConcept.create! valid_attributes
        put :update, {:id => customized_concept.to_param, :customized_concept => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested customized_concept" do
      customized_concept = CustomizedConcept.create! valid_attributes
      expect {
        delete :destroy, {:id => customized_concept.to_param}, valid_session
      }.to change(CustomizedConcept, :count).by(-1)
    end

    it "redirects to the customized_concepts list" do
      customized_concept = CustomizedConcept.create! valid_attributes
      delete :destroy, {:id => customized_concept.to_param}, valid_session
      expect(response).to redirect_to(customized_concepts_url)
    end
  end

end
